// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUEsUxBNFtIC_EC_IsjQyuUg5eeC1jqk',
    appId: '1:1094961899386:web:4556ab8dc61207453d98c3',
    messagingSenderId: '1094961899386',
    projectId: 'fyp-human-face-generator',
    authDomain: 'fyp-human-face-generator.firebaseapp.com',
    storageBucket: 'fyp-human-face-generator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChBu5TNCHD4e3XEcKfItgyuLIbgxrJrAU',
    appId: '1:1094961899386:android:79733e7ea92cadf53d98c3',
    messagingSenderId: '1094961899386',
    projectId: 'fyp-human-face-generator',
    storageBucket: 'fyp-human-face-generator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3_QU3pI-EBEgcclPt3pohTaBdIbcr64',
    appId: '1:1094961899386:ios:ae544d1718dcac923d98c3',
    messagingSenderId: '1094961899386',
    projectId: 'fyp-human-face-generator',
    storageBucket: 'fyp-human-face-generator.appspot.com',
    androidClientId: '1094961899386-uis3s8t9bog9jla2s3c64mu02ujgk7p1.apps.googleusercontent.com',
    iosClientId: '1094961899386-8u62cser4l0qa7aenk4vu3p4e84d52an.apps.googleusercontent.com',
    iosBundleId: 'com.example.humanFaceGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:1094961899386:ios:8e9a31ce61a874123d98c3',
    messagingSenderId: '1094961899386',
    projectId: 'fyp-human-face-generator',
    storageBucket: 'fyp-human-face-generator.appspot.com',
    androidClientId: '1094961899386-uis3s8t9bog9jla2s3c64mu02ujgk7p1.apps.googleusercontent.com',
    iosClientId: '1094961899386-et23alurkn38m6jqgq1e6ggfle52gtkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.humanFaceGenerator.RunnerTests',
  );
}